export const GITHUB_REPOS_LOAD_SUCCESS = 'GITHUB_REPOS_LOAD_SUCCESS'
export const GITHUB_REPOS_LOAD_FAIL = 'GITHUB_REPOS_LOAD_FAIL'
export const GITHUB_INFO_LOAD_SUCCESS = 'GITHUB_INFO_LOAD_SUCCESS'
export const GITHUB_INFO_LOAD_FAIL = 'GITHUB_INFO_LOAD_FAIL'